gcp:
  project: jason-hsbc
  region: europe-west2

# No proxy in production
# proxy:
#   http: http://10.0.1.223:7890
#   https: http://10.0.1.223:7890

deepseek:
  api-key: "DEEPSEEK_API_KEY"
  base-url: "https://api.deepseek.com"
  
database:
  host: "127.0.0.1" # Connect to the Cloud SQL Auth Proxy sidecar
  port: 5432
  dbname: "chatai_prod"
  user: "nvd11"
  password_env_var: "DB_PASSWORD"
